server:
  port: 8082

spring:
  application:
    name: nettyDemo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?charset=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 100
    maxIdle: 20
    initialSize: 5
    maxWait: -1
    minIdle: 5
#    validation-query: SELECT 1 FROM DUAL
    validation-query: SELECT 1
    test-while-idle: true
    testonBorrow: false
    testOnReturn: false
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=50000
  activemq:
    broker-url: tcp://localhost:8161
    user: admin
    password: admin

mybatis:
  type-aliases-package: com.van.netty.model
  mapper-locations: classpath*:mapper/**/*.xml

redis:
  host: 127.0.0.1
  port: 6379
  pool:
    max-active: 8
    max-wait: 1
    max-idle: 8
    min-idle: 0
  timeout: 0